# include javascript.toml

[[layers]]
  name "lang#javascript"
  enable_flow_syntax = true

# [[layers]]
#   name = "lsp"
#   filetypes = ["javascript"]
#   [layers.override_cmd]
#     javascript = ["flow", "lsp"]
